set(_CATKIN_CURRENT_PACKAGE "uart_process_2")
set(uart_process_2_VERSION "0.0.0")
set(uart_process_2_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(uart_process_2_PACKAGE_FORMAT "2")
set(uart_process_2_BUILD_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "message_runtime")
set(uart_process_2_BUILD_EXPORT_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "message_runtime")
set(uart_process_2_BUILDTOOL_DEPENDS "catkin")
set(uart_process_2_BUILDTOOL_EXPORT_DEPENDS )
set(uart_process_2_EXEC_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "message_runtime")
set(uart_process_2_RUN_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "message_runtime")
set(uart_process_2_TEST_DEPENDS )
set(uart_process_2_DOC_DEPENDS )
set(uart_process_2_URL_WEBSITE "")
set(uart_process_2_URL_BUGTRACKER "")
set(uart_process_2_URL_REPOSITORY "")
set(uart_process_2_DEPRECATED "")