set(_CATKIN_CURRENT_PACKAGE "buff")
set(buff_VERSION "0.0.1")
set(buff_MAINTAINER "lss233 <i@lss233.com>")
set(buff_PACKAGE_FORMAT "2")
set(buff_BUILD_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2" "sagitari_debug")
set(buff_BUILD_EXPORT_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2")
set(buff_BUILDTOOL_DEPENDS "catkin")
set(buff_BUILDTOOL_EXPORT_DEPENDS )
set(buff_EXEC_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2" "sagitari_debug")
set(buff_RUN_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2" "sagitari_debug")
set(buff_TEST_DEPENDS )
set(buff_DOC_DEPENDS )
set(buff_URL_WEBSITE "")
set(buff_URL_BUGTRACKER "")
set(buff_URL_REPOSITORY "https://github.com/typical-motion/sagitari")
set(buff_DEPRECATED "")