set(_CATKIN_CURRENT_PACKAGE "camera_file")
set(camera_file_VERSION "0.0.0")
set(camera_file_MAINTAINER "lss233 <lss233@todo.todo>")
set(camera_file_PACKAGE_FORMAT "2")
set(camera_file_BUILD_DEPENDS "cv_bridge" "image_transport" "sensor_msgs")
set(camera_file_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "sensor_msgs")
set(camera_file_BUILDTOOL_DEPENDS "catkin")
set(camera_file_BUILDTOOL_EXPORT_DEPENDS )
set(camera_file_EXEC_DEPENDS "cv_bridge" "image_transport" "sensor_msgs")
set(camera_file_RUN_DEPENDS "cv_bridge" "image_transport" "sensor_msgs")
set(camera_file_TEST_DEPENDS )
set(camera_file_DOC_DEPENDS )
set(camera_file_URL_WEBSITE "")
set(camera_file_URL_BUGTRACKER "")
set(camera_file_URL_REPOSITORY "")
set(camera_file_DEPRECATED "")