set(_CATKIN_CURRENT_PACKAGE "sagitari_debug")
set(sagitari_debug_VERSION "0.0.0")
set(sagitari_debug_MAINTAINER "lss233 <lss233@todo.todo>")
set(sagitari_debug_PACKAGE_FORMAT "2")
set(sagitari_debug_BUILD_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2")
set(sagitari_debug_BUILD_EXPORT_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2")
set(sagitari_debug_BUILDTOOL_DEPENDS "catkin")
set(sagitari_debug_BUILDTOOL_EXPORT_DEPENDS )
set(sagitari_debug_EXEC_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2")
set(sagitari_debug_RUN_DEPENDS "message_generation" "cv_bridge" "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "roslib" "uart_process_2")
set(sagitari_debug_TEST_DEPENDS )
set(sagitari_debug_DOC_DEPENDS )
set(sagitari_debug_URL_WEBSITE "")
set(sagitari_debug_URL_BUGTRACKER "")
set(sagitari_debug_URL_REPOSITORY "")
set(sagitari_debug_DEPRECATED "")